Repository HectorPeeters/fontoxpath, pull requests merged in 2021-06, with the labels that each got.

#108 59 speedup evaluation
  src/expressions/operators/arithmetic/BinaryOperator.ts
  src/expressions/operators/arithmetic/Unary.ts
  src/typeInference/annotateBinaryOperator.ts
  src/typeInference/annotateFlworExpression.ts
  src/typeInference/annotateUnaryOperator.ts
  src/typeInference/annotateVarRef.ts
  test/specs/parsing/operators/numeric/Unary.tests.ts
  test/xqutsTests.ts
Labels: bug

#114 Added general readme to type inference
  src/typeInference/README.md
Labels: documentation

#148 146 optimize value compare
  src/expressions/OrderByExpression.ts
  src/expressions/functions/builtInFunctions_sequences.ts
  src/expressions/operators/compares/Compare.ts
  src/expressions/operators/compares/generalCompare.ts
  src/expressions/operators/compares/valueCompare.ts
  src/parsing/compileAstToExpression.ts
  src/typeInference/README.md
  src/typeInference/annotateFlworExpression.ts
  src/typeInference/annotatePathExpr.ts
  src/typeInference/annotateSequenceOperator.ts
  test/specs/annotation.tests.ts
Labels: optimization

#161 Fix the PR comments from the Fonto PR 377
  .github/workflows/bundlesize.yml
  src/expressions/OrderByExpression.ts
  src/expressions/functions/builtInFunctions_sequences.ts
  src/expressions/operators/compares/Compare.ts
  src/expressions/operators/compares/generalCompare.ts
  src/expressions/operators/compares/nodeCompare.ts
  src/expressions/operators/compares/valueCompare.ts
  src/typeInference/annotateFlworExpression.ts
Labels: bug
